#!/usr/bin/env php
<?php

namespace Behavioral\Mediator;

require_once 'vendor/autoload.php';

$helperHandler = new Handler();
$mediator      = new Mediator();

try {
    $mediator->addListener('listener_1', [new Colleague1(), 'onEvent']);
    $mediator->addListener('listener_2', [new Colleague2(), 'onEvent']);
    $mediator->addListener('listener_3', [Colleague3::class, 'onEvent']);
    $mediator->notify('listener_1');
    $mediator->notify('listener_2', $helperHandler);
    $mediator->notify('listener_3', $helperHandler);
} catch (\Exception $e) {
    echo 'Caught exception: ', $e->getMessage(), "\n";
}
